import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Liberula",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="
        object-cover absolute  bg-liberula-yellow -z-40 shadow-md
        -top-[160px] right-[50px]  w-[600px] h-[410px] rotate-[27deg] 
        mobile-l:-top-[700px] mobile-l:right-[200px]  mobile-l:w-[900px] mobile-l:h-[910px] mobile-l:rotate-[15deg] 
        tablet:-top-[530px] tablet:right-[100px]  tablet:w-[900px] tablet:h-[910px] 
        laptop:-top-[650px] laptop:right-[500px]  laptop:w-[1900px] laptop:h-[910px]
        laptop-l:-top-[600px] laptop-l:right-[800px]  laptop-l:w-[1900px] laptop-l:h-[910px] laptop-l:rotate-[10deg] 
        desktop:-top-[1400px] desktop:right-[800px]  desktop:w-[1900px] desktop:h-[1910px] desktop:shadow-xl 
        "/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
